echo ..............................Change directory...
cd /var/www/app/portal

echo ..............................CLEAN ngcc ngcc clean...
ngcc clean
echo ..............................CLEAN ngcc clear-cache...
ngcc --clear-cache
echo ..............................CLEAN npm cache clean...
npm cache clean --force

echo ..............................Install dependencies Package...
sudo npm install --legacy-perr-deps --loglevel verbose

echo ..............................Build project...
sudo npm run build --prod